import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// 1. CARA IMPORT YANG BENAR (Tanpa kurung kurawal {})
import Navigasi from "./navigasi"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Aplikasi Catat Barang",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="id"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* Ditambahkan bg-gray-50 agar tampilan aplikasi mobile terasa empuk di mata */}
      <body className="min-h-full flex flex-col bg-gray-50">
        
        {/* 2. Diberikan pb-24 agar konten halaman tidak tertutup menu bawah */}
        <main className="flex-1 pb-24">
          {children}
        </main>

        {/* 3. Komponen navigasi melayangmu dipanggil di sini */}
        <Navigasi />
        
      </body>
    </html>
  );
}