import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense } from "react"; // 1. Tambahkan import Suspense
import "./globals.css";
import Navigasi from "./navigasi"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Aplikasi Catat Barang",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="id"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-gray-50">
        
        <main className="flex-1 pb-24">
          {children}
        </main>

        {/* 2. Bungkus dengan Suspense agar build Vercel tidak error */}
        <Suspense fallback={null}>
          <Navigasi />
        </Suspense>
        
      </body>
    </html>
  );
}